spring:
  output:
    ansi:
      enabled: ALWAYS


# swagger-ui custom paths
springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /weather

weather:
  uri: https://samples.openweathermap.org/data/2.5/box/city?bbox=12,32,15,37,10&appid=b6907d289e10d714a6e88b30761fae22

